name: speak
description: "Memorization Flutter Project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.3.0
  fluttertoast: ^8.2.4
  icons_plus: ^5.0.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  date_format: ^2.0.7
  lottie: ^2.7.0
  stepper_list_view: ^0.0.1
  translator: ^0.1.7
  flutter_tts: ^3.8.5
  animated_text_kit: ^4.2.2
  speech_to_text: ^6.5.1
  page_transition: ^2.1.0
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
